name: Test Build

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'

jobs:
  synthesis:
    runs-on: ubuntu-latest
    container: raetro/quartus:17.1
    steps:
      # 1 - Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2
      # 2 - RTL synthesis
      - name: Run compilation flow
        run: quartus_sh --flow compile SH7034.qpf
      # 3 - Upload artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: SH7034.zip
          path: output_files/
      # 2 - RTL synthesis
      - name: Run compilation flow
        run: quartus_sh --flow compile SH7604.qpf
      # 3 - Upload artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: SH7604.zip
          path: output_files/
